version: "3.9"

services:
  # comentar todo o serviço "app" se quiser rodar a aplicação fora de um container; editar aquivo index.ts na pasta shared/infra/typeorm, e o arquivo redis.ts na pasta config
  app:
    build: .
    container_name: "corelab-challenge_api"
    ports:
      - 3333:3333
    command: bash -c "npm run typeorm:development -- -d src/shared/infra/typeorm/index.ts migration:run && npm run dev"
    volumes:
      - .:/user/app
  database:
    image: "postgres"
    container_name: "postgres_corelab-challenge_development"
    restart: "always"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=corelabchallenge
      - POSTGRES_PASSWORD=corelabchallenge
      - POSTGRES_DB=corelab-challenge
      - PGTZ=UTC
    volumes:
      - pgdata:/data/postgres
  test_database:
    image: "postgres"
    container_name: "postgres_corelab-challenge_tests"
    restart: "always"
    ports:
      - 54321:5432
    environment:
      - POSTGRES_USER=corelabchallenge
      - POSTGRES_PASSWORD=corelabchallenge
      - POSTGRES_DB=corelab-challenge_tests
      - PGTZ=UTC
    volumes:
      - pgdata:/data/postgres
  redis:
    image: "redis:alpine"
    container_name: "redis_corelab-challenge_cache_development"
    restart: "always"
    environment:
      - REDIS_PASSWORD=redispassword
    command: >
        --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
  redis_tests:
    image: "redis:alpine"
    container_name: "redis_corelab-challenge_cache_tests"
    restart: "always"
    environment:
      - REDIS_PASSWORD=redispassword
    command: >
        --requirepass ${REDIS_PASSWORD}
    ports:
      - 63791:6379

volumes:
  pgdata:
    driver: local
